steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - --build-arg
      - NEXT_PUBLIC_API_URL=${_API_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}
      - .
images:
  - ${_IMAGE}
options:
  substitution_option: ALLOW_LOOSE
